# Generated by Django 3.0.5 on 2020-10-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_auto_20201020_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('passing_score', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False, verbose_name='Test active?')),
                ('certificate', models.BooleanField(default=False, verbose_name='Test has a certificate')),
            ],
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.CharField(max_length=25)),
                ('test_date', models.DateField(null=True, verbose_name='Date tested')),
                ('cert_printed', models.BooleanField(default=False, verbose_name='Certificate printed?')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Student')),
                ('test_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gems.Test')),
            ],
        ),
    ]
