# Generated by Django 3.0.5 on 2020-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0005_auto_20201024_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='testhistory',
            options={'verbose_name': 'Test History Table', 'verbose_name_plural': 'Test History Table'},
        ),
        migrations.AlterModelOptions(
            name='usertimesheet',
            options={'ordering': ['entryDate'], 'verbose_name': 'Employee Timesheet Table', 'verbose_name_plural': 'Employee Timesheet Table'},
        ),
        migrations.CreateModel(
            name='ClassTimeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Class')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Day')),
                ('hour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Hour')),
            ],
            options={
                'verbose_name': 'Class Time-slots',
                'verbose_name_plural': 'Class Time-slots',
            },
        ),
    ]
