# Generated by Django 3.0.5 on 2020-10-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0006_auto_20201024_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtimeslot',
            options={'verbose_name': 'Class Timeslots', 'verbose_name_plural': 'Class Timeslots'},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment Date')),
                ('class_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.ClassTimeslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Student')),
            ],
            options={
                'verbose_name': 'Student Enrollment Table',
                'verbose_name_plural': 'Student Enrollment Tables',
            },
        ),
    ]
