# Generated by Django 3.0.5 on 2020-10-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0007_auto_20201024_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtimeslot',
            options={'verbose_name': 'Class Timeslot', 'verbose_name_plural': 'Class Timeslots'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Student Enrollment Record', 'verbose_name_plural': 'Student Enrollment Records'},
        ),
        migrations.AlterModelOptions(
            name='testhistory',
            options={'verbose_name': 'Test History Record', 'verbose_name_plural': 'Test History Records'},
        ),
        migrations.AlterModelOptions(
            name='usertimesheet',
            options={'ordering': ['entryDate'], 'verbose_name': 'Employee Timesheet Record', 'verbose_name_plural': 'Employee Timesheet Records'},
        ),
        migrations.RemoveField(
            model_name='classtimeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Day'),
        ),
    ]
