# Generated by Django 3.0.5 on 2020-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0008_auto_20201025_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtimeslot',
            options={'ordering': ('class_name', 'hour'), 'verbose_name': 'Class Timeslot', 'verbose_name_plural': 'Class Timeslots'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('student__last_name', 'enrollment_date'), 'verbose_name': 'Student Enrollment Record', 'verbose_name_plural': 'Student Enrollment Records'},
        ),
        migrations.AddConstraint(
            model_name='classtimeslot',
            constraint=models.UniqueConstraint(fields=('class_name', 'hour'), name='unique_class_timeslot'),
        ),
    ]
