# Generated by Django 3.0.5 on 2020-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0009_auto_20201027_1638'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
    ]
