# Generated by Django 3.0.5 on 2021-01-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('gems', '0011_housingunit_institution'), ('gems', '0012_auto_20201106_1524'), ('gems', '0013_auto_20201204_1634'), ('gems', '0014_auto_20201204_1648'), ('gems', '0015_auto_20201214_1741'), ('gems', '0016_auto_20201218_1655'), ('gems', '0017_auto_20201224_1843'), ('gems', '0018_auto_20210108_1720'), ('gems', '0019_auto_20210111_1630'), ('gems', '0020_auto_20210111_1633'), ('gems', '0021_auto_20210111_1634'), ('gems', '0022_auto_20210111_1635')]

    dependencies = [
        ('gems', '0010_auto_20201027_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='housing_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.HousingUnit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Institution'),
        ),
        migrations.RenameField(
            model_name='testhistory',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='testhistory',
            old_name='test_name',
            new_name='test',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_record',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(verbose_name='Scan Date')),
                ('scan_time', models.TimeField(verbose_name='Scan Time')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Enrollment')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Classroom')),
            ],
            options={
                'verbose_name': 'Student Attendance Record',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ('enrollment__student__last_name', 'enrollment__enrollment_date'),
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'scan_date', 'scan_time'), name='unique_attendance_record'),
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_record',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='scan_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scan_date',
            field=models.DateTimeField(verbose_name='Scan Date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment',), name='unique_attendance_record'),
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_record',
        ),
        migrations.AddField(
            model_name='attendance',
            name='scan_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scan_date',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'scan_date'), name='unique_attendance_record'),
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_record',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_record',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_record',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_record',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'day', 'class_timeslot'), name='unique_enrollment_record'),
        ),
    ]
