# Generated by Django 3.0.5 on 2020-11-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0011_housingunit_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='housing_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.HousingUnit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Institution'),
        ),
    ]
