# Generated by Django 3.0.5 on 2020-12-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0012_auto_20201106_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testhistory',
            old_name='student_name',
            new_name='student',
        ),
    ]
