# Generated by Django 3.0.5 on 2020-12-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0013_auto_20201204_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testhistory',
            old_name='test_name',
            new_name='test',
        ),
    ]
