# Generated by Django 3.0.5 on 2021-01-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0014_auto_20210121_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
