# Generated by Django 3.0.5 on 2020-12-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0015_auto_20201214_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(verbose_name='Scan Date')),
                ('scan_time', models.TimeField(verbose_name='Scan Time')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Enrollment')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.Classroom')),
            ],
            options={
                'verbose_name': 'Student Attendance Record',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ('enrollment__student__last_name', 'enrollment__enrollment_date'),
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'scan_date', 'scan_time'), name='unique_attendance_record'),
        ),
    ]
