# Generated by Django 3.0.5 on 2021-01-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0016_auto_20210123_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('scan_date', 'scan_time'), 'verbose_name': 'Student Attendance Record', 'verbose_name_plural': 'Student Attendance Records'},
        ),
    ]
