# Generated by Django 3.0.5 on 2020-12-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0016_auto_20201218_1655'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_record',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='scan_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scan_date',
            field=models.DateTimeField(verbose_name='Scan Date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment',), name='unique_attendance_record'),
        ),
    ]
