# Generated by Django 3.0.5 on 2021-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0020_auto_20210123_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
