# Generated by Django 3.0.5 on 2021-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0023_auto_20210202_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('barcode',), 'verbose_name': 'Item Record', 'verbose_name_plural': 'Item Records'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='classroom',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='entered_by',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified_by',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='classroom',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='entered_by',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_by',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
