# Generated by Django 3.0.5 on 2021-02-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0024_auto_20210202_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book Record', 'verbose_name_plural': 'Book Records'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item Record', 'verbose_name_plural': 'Item Records'},
        ),
    ]
