# Generated by Django 3.0.5 on 2021-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0026_auto_20210212_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
