# Generated by Django 3.0.5 on 2021-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0027_auto_20210212_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
    ]
