# Generated by Django 3.0.5 on 2021-02-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0031_auto_20210218_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcheckout',
            old_name='book',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='itemcheckout',
            old_name='item',
            new_name='asset',
        ),
    ]
