# Generated by Django 3.0.5 on 2021-02-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0033_auto_20210223_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('barcode',), 'verbose_name': 'Book Record', 'verbose_name_plural': 'Book Records'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('barcode',), 'verbose_name': 'Item Record', 'verbose_name_plural': 'Item Records'},
        ),
    ]
