# Generated by Django 3.0.5 on 2021-03-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0034_auto_20210224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='abbreviated',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
