# Generated by Django 3.0.5 on 2021-03-12 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gems', '0035_day_abbreviated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('entry_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Comment',
                'verbose_name_plural': 'Instructor Comments',
                'permissions': [('can_view_instructor_comments', 'Can view the instructor comments section.')],
            },
        ),
    ]
