# Generated by Django 3.0.5 on 2021-03-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0036_instructorcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',)},
        ),
    ]
