# Generated by Django 3.0.5 on 2021-03-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0037_auto_20210312_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorcomment',
            options={'ordering': ('entry_date',), 'permissions': [('can_view_instructor_comments', 'Can view the instructor comments section.')], 'verbose_name': 'Instructor Comment', 'verbose_name_plural': 'Instructor Comments'},
        ),
    ]
