# Generated by Django 3.0.5 on 2021-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0038_auto_20210312_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
