# Generated by Django 3.0.5 on 2021-03-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0039_instructorcomment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcomment',
            name='modified_by',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='instructorcomment',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
