# Generated by Django 3.0.5 on 2021-04-13 17:35

from django.db import migrations, models
import gems.models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0041_auto_20210412_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='avatar',
            field=models.FilePathField(null=True, path=gems.models.UserSetting.images_path),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.FilePathField(null=True, path=gems.models.UserSetting.themes_path),
        ),
    ]
