from django.contrib import admin

from .models import *

admin.site.register(Student)
admin.site.register(Institution)
admin.site.register(HousingUnit)
admin.site.register(SiteSetting)
admin.site.register(UserSetting)
admin.site.register(UserTimesheet)
admin.site.register(JobTitle)
admin.site.register(Employee)
admin.site.register(Test)
admin.site.register(TestHistory)
admin.site.register(Subject)
admin.site.register(Classroom)
admin.site.register(Teacher)
admin.site.register(Day)
admin.site.register(Hour)
admin.site.register(Class)
admin.site.register(ClassTimeslot)
admin.site.register(Enrollment)
admin.site.register(Attendance)
admin.site.register(ItemCategory)
admin.site.register(Book)
admin.site.register(Item)
admin.site.register(BookCheckout)
admin.site.register(ItemCheckout)
admin.site.register(InstructorComment)