from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

import gems.views as GemsRequests
from gems.feeds import NewStudentFeed

app_name = 'gems'

urlpatterns = [
        path('', GemsRequests.index.as_view(), name='index'),
        path('', include('django.contrib.auth.urls')),
        path('GemsReqJobTitleSelect', GemsRequests.GemsReqJobTitleSelect.as_view()),
        path('GemsReqClassSelect', GemsRequests.GemsReqClassSelect.as_view()),
        path('GemsReqClassroomSelect', GemsRequests.GemsReqClassroomSelect.as_view()),
        path('GemsReqClassroomHourDaySelect', GemsRequests.GemsReqClassroomHourDaySelect.as_view()),
        path('GemsReqAddClassSelect', GemsRequests.GemsReqAddClassSelect.as_view()),
        path('GemsReqAddStudentSelect', GemsRequests.GemsReqAddStudentSelect.as_view()),
        path('GemsReqTestRecordSelect',  GemsRequests.GemsReqTestRecordSelect.as_view()),
        path('GemsReqThemeSelect', GemsRequests.GemsReqThemeSelect.as_view()),
        path('GemsReqAvatarSelect', GemsRequests.GemsReqAvatarSelect.as_view()),
        path('GemsReqEnrollmentRecordSelect',GemsRequests.GemsReqEnrollmentRecordSelect.as_view()),
        path('GemsReqManualAttendanceSelect', GemsRequests.GemsReqManualAttendanceSelect.as_view()),
        path('GemsReqStudentSearch/<str:jsonstr>', GemsRequests.GemsReqStudentSearch.as_view()),
        path('GemsReqEditUserSearch/<str:jsonstr>', GemsRequests.GemsReqEditUserSearch.as_view()),
        path('GemsReqDelUserSearch/<str:jsonstr>', GemsRequests.GemsReqDelUserSearch.as_view()),
        path('GemsReqEditStudentSearch/<str:jsonstr>', GemsRequests.GemsReqEditStudentSearch.as_view()),
        path('GemsReqDelStudentSearch/<str:jsonstr>', GemsRequests.GemsReqDelStudentSearch.as_view()),
        path('GemsReqResetPasswordSearch/<str:jsonstr>',GemsRequests.GemsReqResetPasswordSearch.as_view()),
        path('GemsReqBookSearch/<str:jsonstr>',GemsRequests.GemsReqBookSearch.as_view()),
        path('GemsReqItemSearch/<str:jsonstr>',GemsRequests.GemsReqItemSearch.as_view()), 
        path('GemsReqDisplayStudent', GemsRequests.GemsReqDisplayStudent.as_view()),
        path('GemsReqClassInformation/<str:jsonstr>', GemsRequests.GemsReqClassInformation.as_view()),
        path('GemsReqAddEnrollmentRecord', GemsRequests.GemsReqAddEnrollmentRecord.as_view()),
        path('GemsReqEditEnrollmentRecord', GemsRequests.GemsReqEditEnrollmentRecord.as_view()),
        path('GemsReqDelEnrollmentRecord', GemsRequests.GemsReqDelEnrollmentRecord.as_view()),
        path('GemsReqTestHistory/<str:jsonstr>', GemsRequests.GemsReqTestHistory.as_view()),
        path('GemsReqAddTestRecord', GemsRequests.GemsReqAddTestRecord.as_view()),
        path('GemsReqEditTestRecord', GemsRequests.GemsReqEditTestRecord.as_view()),
        path('GemsReqDelTestRecord', GemsRequests.GemsReqDelTestRecord.as_view()),
        path('GemsReqItemHistory/<str:jsonstr>',GemsRequests.GemsReqItemHistory.as_view()),
        path('GemsReqAddStudent', GemsRequests.GemsReqAddStudent.as_view()),
        path('GemsReqEditStudent', GemsRequests.GemsReqEditStudent.as_view()),
        path('GemsReqDelStudent', GemsRequests.GemsReqDelStudent.as_view()),
        path('GemsReqMoodleInformation/<str:jsonstr>',GemsRequests.GemsReqMoodleInformation.as_view()),
        path('GemsReqStudentComment/<str:jsonstr>',GemsRequests.GemsReqStudentComment.as_view()),
        path('GemsReqAddStudentComment',GemsRequests.GemsReqAddStudentComment.as_view()),
        path('GemsReqDelStudentComment',GemsRequests.GemsReqDelStudentComment.as_view()),
        path('GemsReqPrintStudentBarcodes/<str:jsonstr>',GemsRequests.GemsReqPrintStudentBarcodes.as_view()),
        path('GemsReqUserTimesheet/<str:jsonstr>', GemsRequests.GemsReqUserTimesheet.as_view()),
        path('GemsReqUserTimesheetAddEntry', GemsRequests.GemsReqUserTimesheetAddEntry.as_view()),
        path('GemsReqUserTimesheetEditEntry', GemsRequests.GemsReqUserTimesheetEditEntry.as_view()),
        path('GemsReqUserTimesheetDelEntry', GemsRequests.GemsReqUserTimesheetDelEntry.as_view()),
        path('GemsReqDisplayUserTimesheet/<str:jsonstr>', GemsRequests.GemsReqDisplayUserTimesheet.as_view()),
        path('GemsReqUserChangePassword', GemsRequests.GemsReqUserChangePassword.as_view()),
        path('GemsReqUserChangeTheme', GemsRequests.GemsReqUserChangeTheme.as_view()),
        path('GemsReqPreviewTheme/<str:jsonstr>',GemsRequests.GemsReqPreviewTheme.as_view()),
        path('GemsReqUserChangeAvatar', GemsRequests.GemsReqUserChangeAvatar.as_view()),
        path('GemsReqAdminAddUser', GemsRequests.GemsReqAdminAddUser.as_view()),
        path('GemsReqAdminEditUser', GemsRequests.GemsReqAdminEditUser.as_view()),
        path('GemsReqAdminDelUser', GemsRequests.GemsReqAdminDelUser.as_view()),
        path('GemsReqAdminResetPassword', GemsRequests.GemsReqAdminResetPassword.as_view()),
        path('GemsReqAdminTestManagement', GemsRequests.GemsReqAdminTestManagement.as_view()),
        path('GemsReqAdminAddTest',GemsRequests.GemsReqAdminAddTest.as_view()),
        path('GemsReqAdminEditTest', GemsRequests.GemsReqAdminEditTest.as_view()),
        path('GemsReqAdminDelTest', GemsRequests.GemsReqAdminDelTest.as_view()),
        path('GemsReqAdminClassTSManagement', GemsRequests.GemsReqAdminClassTSManagement.as_view()),
        path('GemsReqAddClassTimeslot', GemsRequests.GemsReqAddClassTimeslot.as_view()),
        path('GemsReqEditClassTimeslot', GemsRequests.GemsReqEditClassTimeslot.as_view()),
        path('GemsReqDelClassTimeslot', GemsRequests.GemsReqDelClassTimeslot.as_view()),
        path('GemsReqAdminClassManagement', GemsRequests.GemsReqAdminClassManagement.as_view()),
        path('GemsReqAdminAddClass', GemsRequests.GemsReqAdminAddClass.as_view()),
        path('GemsReqAdminEditClass', GemsRequests.GemsReqAdminEditClass.as_view()),
        path('GemsReqAdminDelClass', GemsRequests.GemsReqAdminDelClass.as_view()),
        path('GemsReqAdminSubjectManagement', GemsRequests.GemsReqAdminSubjectManagement.as_view()),
        path('GemsReqAdminAddSubject', GemsRequests.GemsReqAdminAddSubject.as_view()),
        path('GemsReqAdminDelSubject', GemsRequests.GemsReqAdminDelSubject.as_view()),
        path('GemsWebAttendance/<str:jsonstr>', GemsRequests.GemsWebAttendance.as_view(), name='web_attendance'),
        path('GemsWebAttendance/GemsReqAddAttendanceRecord/<str:jsonstr>', GemsRequests.GemsReqAddAttendanceRecord.as_view()),
        path('GemsWebAttendance/GemsReqUpdateWebAttendance/<str:jsonstr>', GemsRequests.GemsReqUpdateWebAttendance.as_view()),
        path('GemsReqManualAttendance', GemsRequests.GemsReqManualAttendance.as_view()),
        path('GemsReqDisplayDailyAttendance/<str:jsonstr>', GemsRequests.GemsReqDisplayDailyAttendance.as_view()),
        path('GemsReqDisplayIndividualAttendance/<str:jsonstr>', GemsRequests.GemsReqDisplayIndividualAttendance.as_view()),
        path('GemsReqGenerateCalloutCSV/<str:jsonstr>', GemsRequests.GemsReqGenerateCalloutCSV.as_view()),
        path('GemsReqGenerateClassRoster/<str:jsonstr>', GemsRequests.GemsReqGenerateClassRoster.as_view()),
        path('GemsReqGenerateEnrolledStudents/<str:jsonstr>', GemsRequests.GemsReqGenerateEnrolledStudents.as_view()),
        path('GemsReqGenerateDailyAttendance/<str:jsonstr>', GemsRequests.GemsReqGenerateDailyAttendance.as_view()),
        path('GemsReqGenerateContactHours/<str:jsonstr>', GemsRequests.GemsReqGenerateContactHours.as_view()),
        path('GemsReqGenerateAttendanceScan/<str:jsonstr>', GemsRequests.GemsReqGenerateAttendanceScan.as_view()),
        path('GemsReqGenerateDetails/<str:jsonstr>', GemsRequests.GemsReqGenerateDetails.as_view()),
        path('GemsReqGenerateHistory/<str:jsonstr>', GemsRequests.GemsReqGenerateHistory.as_view()),
        path('GemsReqGenerateAssetsOut/<str:jsonstr>', GemsRequests.GemsReqGenerateAssetsOut.as_view()),
        path('GemsReqGenerateAssetsIn/<str:jsonstr>', GemsRequests.GemsReqGenerateAssetsIn.as_view()),
        path('GemsReqGenerateClassroomInventory/<str:jsonstr>', GemsRequests.GemsReqGenerateClassroomInventory.as_view()),
        path('GemsReqGenerateTestHistory/<str:jsonstr>', GemsRequests.GemsReqGenerateTestHistory.as_view()),
        path('GemsReqEditEducationalAsset', GemsRequests.GemsReqEditEducationalAsset.as_view()),
        path('GemsReqEditEducationalAsset/<str:jsonstr>', GemsRequests.GemsReqEditEducationalAsset.as_view()),
        path('GemsReqDeleteEducationalAsset', GemsRequests.GemsReqDeleteEducationalAsset.as_view()),
        path('GemsReqCheckinEducationalAsset', GemsRequests.GemsReqCheckinEducationalAsset.as_view()),
        path('GemsReqCheckoutEducationalAsset', GemsRequests.GemsReqCheckoutEducationalAsset.as_view()),
        path('GemsReqRenewEducationalAsset', GemsRequests.GemsReqRenewEducationalAsset.as_view()),
        path('GemsReqAddEducationalAsset', GemsRequests.GemsReqAddEducationalAsset.as_view()),
        path('GemsReqAddEducationalAsset/<str:jsonstr>', GemsRequests.GemsReqAddEducationalAsset.as_view()),
        path('GemsReqCopyEducationalAsset', GemsRequests.GemsReqCopyEducationalAsset.as_view()),
        path('GemsReqQuickCheckin', GemsRequests.GemsReqQuickCheckin.as_view()),
        path('GemsReqPrintAssetBarcodes/<str:jsonstr>',GemsRequests.GemsReqPrintAssetBarcodes.as_view()),
        path('students/feed/', NewStudentFeed(), name='students'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
